apiVersion: v1
kind: Service
metadata:
  name: {{ include "meilisearch.fullname" . }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{.Values.service.externalTrafficPolicy}}
  {{- end }}
  type: ClusterIP
  ports:
    - port: {{ .Values.container.containerPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "meilisearch.selectorLabels" . | nindent 4 }}
