apiVersion: v1
kind: Service
metadata:
  name: {{ include "meilisearch.fullname" . }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.container.containerPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "meilisearch.selectorLabels" . | nindent 4 }}
