image:
  # -- Meilisearch image name
  repository: getmeili/meilisearch
  # -- Meilisearch image tag
  tag: v1.8.0
  # -- Meilisearch image pull policy
  pullPolicy: IfNotPresent
  # -- Secret to authenticate against the docker registry
  pullSecret: