image:
  # -- Meilisearch image name
  repository: getmeili/meilisearch
  # -- Meilisearch image tag
  tag: v1.8.0
  # -- Meilisearch image pull policy
  pullPolicy: IfNotPresent
  # -- Secret to authenticate against the docker registry
  pullSecret:

serviceAccount:
  # You can use a specific pre-created service account instead of
  # the one created by this chart.
  # Set create to false to prevent creating a service account and use your own.
  # -- Should this chart create a service account
  create: true
  # -- Custom service account name, if not created by this chart
  name: "meilisearch"
  # -- Additional annotations for created service account
  annotations: {}